default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: 123456
development:
  <<: *default
  database: videoapp_development
test:
  <<: *default
  database: videoapp_test
production:
  <<: *default
  database: videoapp_production